# THEORETICAL QUESTION-

# Q1- Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
#enhance Python's capabilities for numerical operations?


NumPy, short for Numerical Python, is a fundamental library for scientific computing in Python. Its primary purpose is to provide support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Here are some of the key advantages of using NumPy:

### Purpose and Advantages

1. **Multi-dimensional Arrays**:
   - NumPy introduces the `ndarray` object, which is a fast and flexible container for large data sets in Python. It can handle multi-dimensional data, making it essential for numerical computations.

2. **Performance**:
   - NumPy operations are implemented in C, enabling high performance for array computations. This results in faster execution times compared to standard Python lists, especially for large datasets.

3. **Memory Efficiency**:
   - NumPy arrays consume less memory compared to Python lists. They store data more compactly, which is crucial for large-scale data analysis.

4. **Vectorization**:
   - NumPy allows for vectorized operations, meaning you can apply operations to entire arrays without the need for explicit loops. This leads to cleaner code and significant performance improvements.

5. **Broadcasting**:
   - NumPy supports broadcasting, which allows arithmetic operations to be performed on arrays of different shapes without the need for explicit replication of data. This feature simplifies coding and reduces memory overhead.

6. **Comprehensive Mathematical Functions**:
   - NumPy provides a wide range of mathematical functions for performing operations like linear algebra, statistical analysis, Fourier transforms, and more, all optimized for performance.

7. **Interoperability**:
   - NumPy integrates well with other scientific libraries like SciPy, Matplotlib, and Pandas, enabling a seamless workflow for data analysis and visualization.

8. **Ease of Use**:
   - The syntax and structure of NumPy are intuitive for users familiar with Python, making it easier to learn and adopt for scientific computing tasks.

9. **Support for Advanced Operations**:
   - NumPy facilitates advanced mathematical operations, including matrix manipulations, reshaping, slicing, and indexing, which are essential for many scientific applications.

### Enhancing Python’s Capabilities

- **Numerical Operations**: NumPy extends Python’s capabilities by enabling efficient computation of numerical data. With its built-in functions, complex calculations can be performed with minimal code.
  
- **Data Handling**: It simplifies the handling of large datasets, allowing for operations that would be cumbersome with standard Python lists.

- **Integration with Other Libraries**: NumPy forms the backbone for many other scientific libraries, making it indispensable for tasks in data analysis, machine learning, and scientific research.

Overall, NumPy transforms Python into a powerful tool for scientific computing and data analysis, enhancing performance, efficiency, and usability for numerical operations.

# Q2- Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
#other?

Both `np.mean()` and `np.average()` are functions in NumPy that are used to compute the average of an array, but they have some differences in functionality and use cases. Here’s a comparison of the two:

### `np.mean()`

- **Purpose**: Calculates the arithmetic mean of the elements in an array.
- **Syntax**: `np.mean(a, axis=None, dtype=None, out=None, keepdims=False)`
- **Default Behavior**: Computes the mean of all elements in the array unless a specific axis is specified.
- **Use Case**: Use `np.mean()` when you simply want to find the average value of an array or along a specified axis without any weighting.

### Example:
```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)  # Output: 3.0
```

### `np.average()`

- **Purpose**: Computes the weighted average of an array, with an option to specify weights.
- **Syntax**: `np.average(a, axis=None, weights=None, returned=False)`
- **Default Behavior**: If weights are not provided, it behaves similarly to `np.mean()`. However, when weights are provided, it computes the weighted average.
- **Use Case**: Use `np.average()` when you need to calculate the average while considering different weights for the elements. This is particularly useful in scenarios where certain data points should contribute more to the average than others.

### Example:
```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 1, 1, 1, 1])
average_value = np.average(data, weights=weights)  # Output: 3.0

weighted_data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
weighted_average = np.average(weighted_data, weights=weights)  # Output: 4.0
```

### Key Differences

1. **Weights**:
   - `np.mean()`: Does not consider weights.
   - `np.average()`: Can consider weights, allowing for a more flexible average calculation.

2. **Output**:
   - Both functions return the same type of result when weights are not used, but `np.average()` can return a tuple when the `returned` parameter is set to `True`, providing the weighted average and the sum of weights.

3. **Functionality**:
   - `np.mean()` is straightforward and intended for simple mean calculations.
   - `np.average()` is more versatile, allowing for weighted calculations and thus can be used in more complex scenarios.

### When to Use One Over the Other

- **Use `np.mean()`**: When you want a straightforward calculation of the average without weights or additional complexity.
  
- **Use `np.average()`**: When you need to compute an average that accounts for the importance or frequency of individual elements (i.e., using weights).

In summary, choose based on whether you need a simple mean or a weighted average for your data analysis task.

# Q3- Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
#arrays.

Reversing a NumPy array can be done in several ways, depending on whether you are working with a one-dimensional (1D) or two-dimensional (2D) array, and along which axis you want to reverse it. Here are the methods for both 1D and 2D arrays:

### Reversing a 1D Array

For a 1D array, you can reverse it using slicing.

#### Example:

```python
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array using slicing
reversed_array_1d = array_1d[::-1]

print(reversed_array_1d)  # Output: [5 4 3 2 1]
```

### Reversing a 2D Array

For a 2D array, you can reverse it along different axes using slicing or the `np.flip()` function.

#### Example of Reversing along Different Axes:

1. **Reversing along the first axis (rows)**:
   - This will flip the array upside down.

```python
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Reverse the array along the first axis (rows)
reversed_rows = array_2d[::-1]

print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
```

2. **Reversing along the second axis (columns)**:
   - This will flip the array left to right.

```python
# Reverse the array along the second axis (columns)
reversed_columns = array_2d[:, ::-1]

print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]
```

3. **Reversing along both axes**:
   - This will flip the array both upside down and left to right.

```python
# Reverse the array along both axes
reversed_both = array_2d[::-1, ::-1]

print(reversed_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]
```

### Using `np.flip()`

You can also use the `np.flip()` function, which allows you to specify the axis along which to reverse the array.

- **Flip along the first axis (rows)**:

```python
flipped_rows = np.flip(array_2d, axis=0)
print(flipped_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
```

- **Flip along the second axis (columns)**:

```python
flipped_columns = np.flip(array_2d, axis=1)
print(flipped_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]
```

- **Flip along both axes**:

```python
flipped_both = np.flip(array_2d, axis=(0, 1))
print(flipped_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]
```

### Summary

- **1D Arrays**: Reversed using slicing (`array[::-1]`).
- **2D Arrays**: Can be reversed along different axes using slicing or `np.flip()`.
- **Slicing**: Use `array[::-1]` for rows and `array[:, ::-1]` for columns.
- **`np.flip()`**: A more flexible way to reverse arrays along specified axes.

These methods provide efficient and concise ways to reverse arrays in NumPy!

#Q4- How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
#in memory management and performance.

In NumPy, you can determine the data type of elements in an array using the `.dtype` attribute. Here’s how to do it, along with a discussion on the importance of data types in memory management and performance.

### Determining Data Type of Elements

To find the data type of a NumPy array, you simply access the `.dtype` attribute of the array. Here's an example:

#### Example:

```python
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Determine the data type
data_type = array.dtype

print(data_type)  # Output: int64 (or int32 depending on the platform)
```

You can also create arrays with specific data types using the `dtype` parameter:

```python
# Create a NumPy array with a specified data type
array_float = np.array([1.0, 2.0, 3.0], dtype=np.float32)

print(array_float.dtype)  # Output: float32
```

### Importance of Data Types in Memory Management and Performance

1. **Memory Efficiency**:
   - Different data types consume different amounts of memory. For example, an `int32` takes 4 bytes, while an `int64` takes 8 bytes. Using the smallest necessary data type can significantly reduce the overall memory footprint, especially in large arrays.

2. **Performance**:
   - Operations on arrays can be faster with certain data types. For instance, floating-point operations may be slower than integer operations due to the additional complexity in handling floating-point arithmetic.
   - Smaller data types can improve cache efficiency, leading to faster access and processing times.

3. **Precision**:
   - Choosing the correct data type affects the precision of numerical computations. For example, using `float32` instead of `float64` may lead to precision loss in calculations, which can be critical in scientific computing or data analysis.

4. **Compatibility**:
   - Certain operations or functions may require specific data types. Understanding and managing data types is essential for ensuring compatibility and correctness in calculations, especially when combining multiple arrays or using libraries that depend on NumPy.

5. **Type Promotion**:
   - NumPy automatically promotes data types in certain operations (e.g., adding an integer to a float will result in a float). Being aware of data types helps prevent unintended behavior and errors in calculations.

6. **Interoperability with Other Libraries**:
   - Many libraries that work with NumPy (like SciPy, Pandas, and others) rely on NumPy’s data types. Proper management of data types can ensure smooth integration and performance when working across these libraries.

### Summary

To determine the data type of a NumPy array, use the `.dtype` attribute. Data types play a crucial role in memory management and performance, affecting memory usage, computational speed, precision, and compatibility with functions and libraries. Selecting appropriate data types is essential for efficient numerical computing and data analysis in Python.





#Q5- Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, `ndarray` (short for "N-dimensional array") is a core data structure designed for efficient numerical computing and data manipulation. Here's a comprehensive overview of `ndarrays`, their key features, and how they differ from standard Python lists.

### Definition of `ndarray`

An `ndarray` is a multi-dimensional array object that allows you to store and manipulate large datasets in a structured way. All elements in an `ndarray` are of the same data type, which can be specified upon creation. The shape of the array (i.e., its dimensions) can vary, allowing for complex data representations.

### Key Features of `ndarrays`

1. **Homogeneous Data Type**:
   - All elements in an `ndarray` must be of the same type (e.g., all integers or all floats). This homogeneity ensures efficient memory usage and optimized performance during calculations.

2. **N-dimensional**:
   - `ndarrays` can be one-dimensional, two-dimensional, three-dimensional, or even higher-dimensional, making them versatile for various applications, including matrices and tensors.

3. **Contiguous Memory Allocation**:
   - `ndarrays` are stored in contiguous blocks of memory, which enhances performance by improving cache locality and reducing memory fragmentation.

4. **Broadcasting**:
   - NumPy supports broadcasting, which allows operations on arrays of different shapes without needing to replicate data explicitly. This feature simplifies arithmetic operations and enhances performance.

5. **Vectorized Operations**:
   - Operations on `ndarrays` can be performed element-wise without using explicit loops, thanks to vectorization. This leads to more readable code and significant performance improvements.

6. **Rich Functionality**:
   - NumPy provides a wide array of built-in functions for mathematical operations, statistical analysis, linear algebra, and more, all optimized for `ndarrays`.

7. **Advanced Indexing and Slicing**:
   - `ndarrays` support advanced indexing and slicing techniques, allowing easy access and manipulation of subarrays.

8. **Shape and Reshaping**:
   - You can easily query and modify the shape of an `ndarray`. Reshaping is efficient and can be done without copying the underlying data.

9. **Memory Efficiency**:
   - Compared to standard Python lists, `ndarrays` use memory more efficiently due to their fixed data types and contiguous storage.

### Differences from Standard Python Lists

1. **Data Type**:
   - **`ndarray`**: Homogeneous; all elements must be of the same type.
   - **Python List**: Heterogeneous; can contain elements of different types (e.g., integers, strings, other lists).

2. **Performance**:
   - **`ndarray`**: Optimized for numerical operations, leading to faster computations, especially for large datasets.
   - **Python List**: Generally slower for numerical tasks due to dynamic typing and the overhead of managing mixed data types.

3. **Memory Usage**:
   - **`ndarray`**: More memory-efficient, as it allocates memory in contiguous blocks and does not store type information for each element.
   - **Python List**: Consumes more memory due to the flexibility of storing different types and additional overhead for each element.

4. **Functionality**:
   - **`ndarray`**: Offers a rich set of mathematical and statistical functions that can be applied directly to the array.
   - **Python List**: Limited to basic operations (e.g., appending, slicing); does not natively support advanced mathematical operations.

5. **Dimension**:
   - **`ndarray`**: Can easily represent and manipulate multi-dimensional data (e.g., 2D matrices).
   - **Python List**: Can represent multi-dimensional data using nested lists, but this is less efficient and more cumbersome.

### Summary

`ndarrays` in NumPy are specialized data structures designed for efficient numerical computing and data analysis. They offer significant advantages over standard Python lists in terms of performance, memory efficiency, and functionality, making them essential for scientific computing, data analysis, and machine learning tasks in Python.

#Q6- Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays offer significant performance benefits over standard Python lists, especially for large-scale numerical operations. Here’s an analysis of these benefits:

### 1. **Memory Efficiency**

- **Contiguous Memory Allocation**: NumPy arrays are stored in contiguous blocks of memory, which allows for more efficient use of memory and better cache performance. This is crucial when handling large datasets, as it reduces memory fragmentation and overhead.
- **Fixed Data Types**: NumPy arrays require all elements to be of the same data type, allowing for more compact storage. In contrast, Python lists can store elements of different types, which incurs additional memory overhead.

### 2. **Faster Computation**

- **Vectorization**: NumPy enables vectorized operations, allowing mathematical operations to be applied to entire arrays at once without explicit loops. This leads to a significant reduction in execution time compared to iterating through elements in a Python list.
  
  **Example**:
  ```python
  import numpy as np
  import time

  # Using NumPy
  array = np.arange(1_000_000)
  start = time.time()
  np_sum = np.sum(array)
  print("NumPy sum:", np_sum)
  print("NumPy time:", time.time() - start)

  # Using Python list
  py_list = list(range(1_000_000))
  start = time.time()
  py_sum = sum(py_list)
  print("Python list sum:", py_sum)
  print("Python list time:", time.time() - start)
  ```

### 3. **Optimized Operations**

- **Built-in Functions**: NumPy provides a wide range of optimized built-in functions for operations like linear algebra, statistical calculations, and element-wise operations. These functions are implemented in C, offering significant speed advantages over Python's native operations.

### 4. **Broadcasting Capabilities**

- **Efficient Operations on Arrays of Different Shapes**: NumPy's broadcasting allows for arithmetic operations between arrays of different shapes without the need to manually expand them. This feature enables more complex computations without sacrificing performance.
  
  **Example**:
  ```python
  import numpy as np
  
  # Two arrays of different shapes
  a = np.array([[1, 2, 3], [4, 5, 6]])
  b = np.array([1, 2, 3])
  
  # Broadcasting allows addition without explicit replication
  result = a + b
  ```

### 5. **Reduced Overhead for Large Datasets**

- **Less Overhead with Array Operations**: When performing operations on large datasets, the overhead of managing Python objects (like lists) can slow down performance. NumPy minimizes this overhead, providing a more streamlined approach to handling data.

### 6. **Multithreading and Parallelism**

- **Multithreading Support**: NumPy operations can utilize multithreading and optimized libraries (like BLAS and LAPACK) to leverage CPU capabilities fully. This results in faster computations, especially for large-scale numerical tasks.

### 7. **Performance Profiling**

- **Profiling Capabilities**: Tools like `%timeit` in Jupyter notebooks can demonstrate the performance differences clearly. Users can visually observe the time savings when using NumPy arrays versus Python lists for various operations.

### Conclusion

The performance benefits of NumPy arrays over Python lists for large-scale numerical operations are substantial. They include improved memory efficiency, faster computation through vectorization, optimized built-in functions, broadcasting capabilities, reduced overhead, and multithreading support. These advantages make NumPy an essential tool for scientists, engineers, and data analysts working with large datasets and complex numerical computations.

#Q7- Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
#output.

In NumPy, the `vstack()` and `hstack()` functions are used to stack arrays vertically and horizontally, respectively. Here's a detailed comparison along with examples demonstrating their usage.

### `vstack()`

**Functionality**: The `vstack()` function stacks arrays in sequence vertically (row-wise). It takes a tuple of arrays and returns a new array that is formed by stacking the input arrays on top of each other.

**Usage**:
```python
import numpy as np

# Create two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically
vstack_result = np.vstack((a, b))

print("vstack result:\n", vstack_result)
```

**Output**:
```
vstack result:
 [[1 2 3]
 [4 5 6]]
```

### `hstack()`

**Functionality**: The `hstack()` function stacks arrays in sequence horizontally (column-wise). Similar to `vstack()`, it takes a tuple of arrays and returns a new array formed by stacking the input arrays side by side.

**Usage**:
```python
# Create two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack horizontally
hstack_result = np.hstack((a, b))

print("hstack result:\n", hstack_result)
```

**Output**:
```
hstack result:
 [1 2 3 4 5 6]
```

### Example with 2D Arrays

You can also use `vstack()` and `hstack()` with 2D arrays.

#### Using `vstack()` with 2D Arrays

```python
# Create two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Stack vertically
vstack_2d_result = np.vstack((array1, array2))

print("Vertical stack result:\n", vstack_2d_result)
```

**Output**:
```
Vertical stack result:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
```

#### Using `hstack()` with 2D Arrays

```python
# Stack horizontally
hstack_2d_result = np.hstack((array1, array2))

print("Horizontal stack result:\n", hstack_2d_result)
```

**Output**:
```
Horizontal stack result:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
```

### Summary

- **`vstack()`**:
  - Stacks arrays vertically (row-wise).
  - Each input array is added as a new row in the resulting array.

- **`hstack()`**:
  - Stacks arrays horizontally (column-wise).
  - Each input array is added as a new column in the resulting array.

These functions are useful for combining arrays in different orientations, making data manipulation and preparation tasks easier in NumPy.

#Q8- Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
#array dimensions.

In NumPy, the `fliplr()` and `flipud()` functions are used to flip arrays left to right and up to down, respectively. Here’s a detailed explanation of the differences between these two functions, including their effects on various array dimensions.

### `fliplr()`

**Functionality**:
- The `fliplr()` function flips an array in the left/right direction (i.e., along the vertical axis). This means that the first column of the array becomes the last, the second column becomes the second to last, and so on.

**Usage**:
- It is typically used with 2D arrays (though it can be applied to 1D arrays, which will not have a visible effect).

**Example**:
```python
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flip left to right
fliplr_result = np.fliplr(array_2d)

print("Original array:\n", array_2d)
print("Flipped left to right:\n", fliplr_result)
```

**Output**:
```
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped left to right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
```

### `flipud()`

**Functionality**:
- The `flipud()` function flips an array up/down (i.e., along the horizontal axis). This means that the first row of the array becomes the last, the second row becomes the second to last, and so forth.

**Usage**:
- Like `fliplr()`, `flipud()` is typically used with 2D arrays, but it can also be applied to 1D arrays, resulting in the same effect as reversing the array.

**Example**:
```python
# Flip up to down
flipud_result = np.flipud(array_2d)

print("Original array:\n", array_2d)
print("Flipped up to down:\n", flipud_result)
```

**Output**:
```
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped up to down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
```

### Effects on Various Array Dimensions

1. **1D Arrays**:
   - Both `fliplr()` and `flipud()` will yield the same result for 1D arrays, which is simply reversing the order of elements.
   
   **Example**:
   ```python
   array_1d = np.array([1, 2, 3, 4])
   print(np.fliplr(array_1d))  # Output: [4 3 2 1]
   print(np.flipud(array_1d))  # Output: [4 3 2 1]
   ```

2. **2D Arrays**:
   - **`fliplr()`**: Flips the array along the vertical axis, changing the order of columns.
   - **`flipud()`**: Flips the array along the horizontal axis, changing the order of rows.
   
3. **3D Arrays**:
   - **`fliplr()`** and **`flipud()`** can also be applied to 3D arrays, but they will only flip the last two dimensions (effectively treating each 2D slice along the first dimension separately).
   - For example, if you have a 3D array, `fliplr()` will flip each 2D slice left to right, while `flipud()` will flip each slice up to down.

### Summary

- **`fliplr()`**:
  - Flips an array left to right (vertical flip).
  - Primarily affects the columns of the array.

- **`flipud()`**:
  - Flips an array up to down (horizontal flip).
  - Primarily affects the rows of the array.

These functions are useful for manipulating the orientation of arrays, especially in image processing, data analysis, and numerical computations where the arrangement of data matters.

# Q9- Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The `array_split()` method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It offers flexibility in dividing arrays, particularly useful when you need to work with smaller segments of data.

### Functionality of `array_split()`

1. **Basic Syntax**:
   ```python
   numpy.array_split(ary, indices_or_sections, axis=0)
   ```
   - **`ary`**: The input array to be split.
   - **`indices_or_sections`**: This can be an integer or a sequence of indices. If it’s an integer, it indicates the number of equal (or approximately equal) splits. If it’s a sequence, it specifies the indices at which to split the array.
   - **`axis`**: The axis along which to split the array. The default is `0`, which means splitting along the first axis (rows for 2D arrays).

2. **Return Value**:
   - The function returns a list of sub-arrays.

### Handling Uneven Splits

When using `array_split()`, if the number of elements in the original array cannot be evenly divided by the number of sections specified, it handles the splits by distributing the elements as evenly as possible. Here’s how it works:

- If the number of sections is **not an exact divisor** of the array size, some sub-arrays may contain one more element than others.
- The split is made such that the leftmost sub-arrays will contain the extra elements if the original array’s size is not perfectly divisible by the number of splits.

### Examples

#### Example 1: Basic Usage

```python
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split into 3 parts
split_result = np.array_split(array_1d, 3)

print("Split result:", split_result)
```

**Output**:
```
Split result: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
```

#### Example 2: Uneven Splits

```python
# Create a 1D array with an uneven split
array_1d_uneven = np.array([1, 2, 3, 4, 5])

# Split into 3 parts
uneven_split_result = np.array_split(array_1d_uneven, 3)

print("Uneven split result:", uneven_split_result)
```

**Output**:
```
Uneven split result: [array([1, 2]), array([3, 4]), array([5])]
```

In this case, the first two sub-arrays contain 2 elements each, and the last sub-array contains the remaining single element.

#### Example 3: Splitting a 2D Array

```python
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

# Split into 2 parts along the first axis (rows)
split_2d_result = np.array_split(array_2d, 2, axis=0)

print("2D Split result:")
for arr in split_2d_result:
    print(arr)
```

**Output**:
```
2D Split result:
 [[1 2 3]
 [4 5 6]]
 [[ 7  8  9]
 [10 11 12]]
```

### Summary

- The `array_split()` method is a flexible way to divide arrays into sub-arrays in NumPy.
- It can handle uneven splits by distributing the extra elements to the leftmost sub-arrays when the total number of elements is not divisible by the number of sections.
- This functionality is particularly useful in data processing tasks where you need to handle data in smaller, manageable chunks.

#10- Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
#operations?

Vectorization and broadcasting are two key concepts in NumPy that significantly enhance the efficiency and performance of array operations. Here’s a detailed explanation of both concepts and how they contribute to efficient computations.

### Vectorization

**Definition**:
Vectorization refers to the practice of applying operations to entire arrays or large blocks of data at once, instead of using explicit loops to iterate over individual elements. This is made possible by NumPy's underlying implementation, which leverages optimized C and Fortran code.

**Benefits**:
1. **Performance Improvement**: Vectorized operations are generally faster than their iterative counterparts because they minimize the overhead associated with Python’s loop constructs and take advantage of low-level optimizations.
2. **Concise Code**: Using vectorized operations results in cleaner, more readable code, making it easier to understand and maintain.
3. **Reduced Complexity**: Vectorization abstracts away the complexity of element-wise operations, allowing users to focus on high-level computations.

**Example**:
Instead of summing two arrays element-wise using a loop:
```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Using a loop
result = np.empty_like(a)
for i in range(len(a)):
    result[i] = a[i] + b[i]
```
You can use vectorization:
```python
# Vectorized operation
result = a + b
```

### Broadcasting

**Definition**:
Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands the smaller array to match the shape of the larger array, enabling element-wise operations without requiring explicit replication of data.

**How Broadcasting Works**:
1. **Shape Compatibility**: For two arrays to be broadcast together, their shapes must be compatible. This means:
   - If they have a different number of dimensions, the shape of the smaller-dimensional array is padded with ones on the left until both shapes have the same length.
   - The size of the dimensions must be either the same or one of them must be 1.
  
2. **Expansion**: When performing operations, NumPy virtually expands the smaller array along the dimensions of the larger one. This expansion is conceptual; it does not actually copy the data, which helps save memory.

**Example**:
Consider a 1D array being added to a 2D array:
```python
import numpy as np

# Create a 2D array and a 1D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# Broadcasting adds the 1D array to each row of the 2D array
result = array_2d + array_1d

print("Result:\n", result)
```

**Output**:
```
Result:
 [[11 22 33]
 [14 25 36]]
```

In this example, the 1D array is effectively broadcast to match the shape of the 2D array, allowing for element-wise addition without the need for manual replication.

### Contributions to Efficient Array Operations

1. **Speed**: Both vectorization and broadcasting leverage optimized algorithms that can operate on large datasets efficiently, greatly speeding up computations compared to traditional loop-based approaches.
  
2. **Memory Efficiency**: By avoiding unnecessary data replication (as in the case of broadcasting), these techniques minimize memory usage, which is particularly important when dealing with large datasets.

3. **Ease of Use**: They simplify the syntax and structure of code, making numerical computations more intuitive and easier to implement.

4. **Scalability**: The ability to efficiently handle operations across different shapes and sizes of arrays allows for more flexible and scalable data processing, making it easier to work with complex datasets.

### Summary

- **Vectorization** enables efficient array operations by applying functions to entire arrays at once, leading to improved performance and cleaner code.
- **Broadcasting** allows for operations on arrays of different shapes by expanding smaller arrays to match larger ones, facilitating element-wise computations without manual data replication.
- Together, these concepts make NumPy a powerful tool for scientific computing, data analysis, and machine learning.

# PRACTICAL QUESTIONS

#Q1- Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

You can create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns using the `numpy` library. Here's how you can do that:

```python
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print("Original array:\n", array_3x3)

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T
print("\nTransposed array:\n", transposed_array)
```

### Explanation:
1. **Creating the Array**: The `np.random.randint(1, 101, size=(3, 3))` function generates a 3x3 array of random integers between 1 and 100.
2. **Transposing**: The `.T` attribute is used to interchange the rows and columns of the array, effectively transposing it.

### Sample Output
When you run the code, you might see output similar to this (note that the random values will change each time):

```
Original array:
 [[45 12 67]
 [23 34 89]
 [56 78 90]]

Transposed array:
 [[45 23 56]
 [12 34 78]
 [67 89 90]]
```

This shows the original array and its transposed version, where the rows and columns have been interchanged.

#Q2- Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

You can create a 1D NumPy array with 10 elements and then reshape it into both a 2x5 array and a 5x2 array using the `numpy` library. Here’s how to do that:

```python
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # This creates an array with values from 0 to 9
print("Original 1D array:\n", array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 array:\n", array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 array:\n", array_5x2)
```

### Explanation:
1. **Creating the 1D Array**: The `np.arange(10)` function generates a 1D array with elements ranging from 0 to 9.
2. **Reshaping**: The `reshape()` method is used to change the shape of the array to the specified dimensions (2x5 and 5x2).

### Sample Output
When you run the code, the output will look something like this:

```
Original 1D array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```

This output shows the original 1D array and its two reshaped forms, demonstrating how the data is reorganized into different dimensions.

# Q3- Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

You can create a 4x4 NumPy array with random float values and then add a border of zeros around it to create a 6x6 array using the `numpy` library. Here's how to do that:

```python
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.random((4, 4))
print("Original 4x4 array:\n", array_4x4)

# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 array with a border of zeros:\n", array_with_border)
```

### Explanation:
1. **Creating the 4x4 Array**: The `np.random.random((4, 4))` function generates a 4x4 array with random float values between 0.0 and 1.0.
2. **Adding a Border**: The `np.pad()` function is used to add a border of zeros. The `pad_width=1` argument specifies that a border of one unit should be added around all sides of the array. The `mode='constant'` and `constant_values=0` arguments specify that the padding should be filled with zeros.

### Sample Output
When you run the code, the output might look something like this:

```
Original 4x4 array:
 [[0.16134256 0.9874894  0.87063761 0.32973249]
 [0.70137737 0.85673964 0.0996607  0.64277932]
 [0.79499436 0.09881248 0.31078808 0.63058672]
 [0.9032639  0.48266926 0.2631682  0.0477927 ]]

6x6 array with a border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.16134256 0.9874894  0.87063761 0.32973249 0.        ]
 [0.         0.70137737 0.85673964 0.0996607  0.64277932 0.        ]
 [0.         0.79499436 0.09881248 0.31078808 0.63058672 0.        ]
 [0.         0.9032639  0.48266926 0.2631682  0.0477927  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
```

This output shows the original 4x4 array with random float values and the resulting 6x6 array with a border of zeros surrounding it.

# Q4- Using NumPy, create an array of integers from 10 to 60 with a step of 5.

You can create an array of integers from 10 to 60 with a step of 5 using the `numpy` library. This can be accomplished using the `numpy.arange()` function. Here’s how to do it:

```python
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:\n", array_integers)
```

### Explanation:
- The `np.arange(start, stop, step)` function generates values starting from `start` (10) up to (but not including) `stop` (61), with the specified `step` (5).

### Sample Output
When you run the code, you will get the following output:

```
Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]
```

This output shows the desired array of integers from 10 to 60, inclusive, with a step of 5.

#Q5- Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

You can create a NumPy array of strings and then apply various case transformations (uppercase, lowercase, title case, etc.) to each element using NumPy's string methods. Here’s how to do it:

```python
import numpy as np

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array_strings)
lowercase_array = np.char.lower(array_strings)
titlecase_array = np.char.title(array_strings)
capitalize_array = np.char.capitalize(array_strings)

# Print the results
print("Original array:", array_strings)
print("Uppercase array:", uppercase_array)
print("Lowercase array:", lowercase_array)
print("Titlecase array:", titlecase_array)
print("Capitalized array:", capitalize_array)
```

### Explanation:
1. **Creating the Array**: The `np.array()` function creates a NumPy array of strings.
2. **Applying Transformations**:
   - `np.char.upper()`: Converts each string in the array to uppercase.
   - `np.char.lower()`: Converts each string in the array to lowercase.
   - `np.char.title()`: Converts each string to title case (first letter of each word capitalized).
   - `np.char.capitalize()`: Capitalizes the first letter of each string, making all other letters lowercase.

### Sample Output
When you run the code, you might see output similar to this:

```
Original array: ['python' 'numpy' 'pandas']
Uppercase array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array: ['python' 'numpy' 'pandas']
Titlecase array: ['Python' 'Numpy' 'Pandas']
Capitalized array: ['Python' 'Numpy' 'Pandas']
```

This output shows the original array and the results of the various case transformations applied to each element.

# Q6- Generate a NumPy array of words. Insert a space between each character of every word in the array

You can generate a NumPy array of words and then insert a space between each character of every word using NumPy's string operations. Here's how you can do that:

```python
import numpy as np

# Create a NumPy array of words
array_words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', array_words)

# Print the results
print("Original array:", array_words)
print("Array with spaces between characters:")
for word in spaced_words:
    print(word)
```

### Explanation:
1. **Creating the Array**: The `np.array()` function creates a NumPy array of words.
2. **Inserting Spaces**: The `np.char.join(' ', array_words)` method joins each character of the words in the array with a space.

### Sample Output
When you run the code, you might see output similar to this:

```
Original array: ['python' 'numpy' 'pandas']
Array with spaces between characters:
p y t h o n
n u m p y
p a n d a s
```

This output shows the original array and the new array with spaces inserted between each character of every word.

# Q7- Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

You can create two 2D NumPy arrays and then perform element-wise addition, subtraction, multiplication, and division using standard arithmetic operators. Here’s how to do it:

```python
import numpy as np

# Create two 2D NumPy arrays
array_1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
array_2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

# Perform element-wise operations
addition = array_1 + array_2
subtraction = array_1 - array_2
multiplication = array_1 * array_2
division = array_1 / array_2

# Print the results
print("Array 1:\n", array_1)
print("\nArray 2:\n", array_2)
print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)
```

### Explanation:
1. **Creating the Arrays**: Two 2D arrays, `array_1` and `array_2`, are created using `np.array()`.
2. **Element-wise Operations**:
   - **Addition**: Uses the `+` operator.
   - **Subtraction**: Uses the `-` operator.
   - **Multiplication**: Uses the `*` operator.
   - **Division**: Uses the `/` operator.

### Sample Output
When you run the code, the output might look like this:

```
Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[ -6  -6  -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[  7  16  27]
 [ 40  55  72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
```

This output shows the two original arrays and the results of the element-wise addition, subtraction, multiplication, and division operations.

# Q8- Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

You can create a 5x5 identity matrix using NumPy and then extract its diagonal elements using the `numpy` library. Here’s how to do it:

```python
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)
```

### Explanation:
1. **Creating the Identity Matrix**: The `np.eye(5)` function generates a 5x5 identity matrix, where all the diagonal elements are 1, and all other elements are 0.
2. **Extracting Diagonal Elements**: The `np.diagonal()` function retrieves the diagonal elements of the matrix.

### Sample Output
When you run the code, the output might look like this:

```
5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]
```

This output shows the 5x5 identity matrix and the diagonal elements extracted from it, which are all 1s.

# Q9- Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.

To generate a NumPy array of 100 random integers between 0 and 1000 and then find and display all prime numbers in that array, you can use the following approach:

```python
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Random integers:\n", random_integers)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the prime numbers
print("\nPrime numbers in the array:", prime_numbers)
```

### Explanation:
1. **Generating Random Integers**: The `np.random.randint(0, 1001, size=100)` function generates an array of 100 random integers between 0 and 1000.
2. **Prime Checking Function**: The `is_prime()` function checks if a number is prime. It returns `False` for numbers less than or equal to 1, and checks divisibility for numbers greater than 1.
3. **Finding Prime Numbers**: A list comprehension iterates through the random integers, using the `is_prime()` function to filter out prime numbers.
4. **Display Results**: Finally, it prints the list of prime numbers found in the array.

### Sample Output
When you run the code, the output might look something like this:

```
Random integers:
 [ 334  285  537  252  331  577  552  256  940  112  661  341  768  994  895
  992  730  135  128  370  293  166  903  859  298  298  886  195  361  646
  195  750  489  303  606  182  751  473  375  509  898  232  620  353  126
  228  230  703  411  558  600  898  844  393  800  273  809  624  983  640
  853  680  676  421  199  117  646  989  251  139  736  677  509  222  903
  513  313  663  327  231  118  411  950  226  199  762  663  838  468  495
  550  531  314  116  754  440  800  775  641  815  550  767  626  291  196]

Prime numbers in the array: [331, 577, 661, 293, 859, 751, 473, 509, 353, 421, 199, 683, 809, 983, 853, 199, 139, 677, 509, 313]
```

This output shows the generated random integers and the list of prime numbers extracted from that array. The specific numbers will vary with each execution due to the randomness.

# Q10- Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages.

To create a NumPy array representing daily temperatures for a month and calculate the weekly averages, you can follow these steps. Here's how you can do it using Python and NumPy:

```python
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.randint(low=15, high=35, size=30)  # Temperatures between 15 and 35

# Display the daily temperatures
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Calculate weekly averages
# Reshape the array to have 4 weeks (each with 7 days) and handle the remaining days
weekly_averages = []

# Loop through each week (there are 4 full weeks in 30 days)
for i in range(0, len(daily_temperatures), 7):
    week = daily_temperatures[i:i+7]  # Get the temperatures for the week
    weekly_averages.append(np.mean(week))  # Calculate the average for the week

# Convert the list of weekly averages to a NumPy array
weekly_averages = np.array(weekly_averages)

# Display the weekly averages
print("\nWeekly Averages:")
print(weekly_averages)
```

### Explanation:
1. **Daily Temperatures**: We generate random integers between 15 and 35 to simulate daily temperatures over a month (30 days).
2. **Weekly Averages**: We loop through the `daily_temperatures` array in chunks of 7 days, calculating the mean for each week.
3. **Display**: Finally, we print the daily temperatures and the calculated weekly averages.

You can run this code in a Python environment where NumPy is installed to see the output.